Add French translation courtesy of ON7CL
Add debugging info in addstatic to help diagnose zip download corruption
Add trace messages in glv/flash/flashdb

diff --git a/addstatic b/addstatic
--- a/addstatic
+++ b/addstatic
@@ -19,7 +19,7 @@
 #  This script is automatically called from exec.post
 #  no need to call this manually anymore. In fact, don't.
 # 
-
+. ~/md380tools-vm/strings
 
 FILESTATIC=~/static.users
 FILESEED=user.seed
@@ -40,7 +40,7 @@ if [ -f $STATICFILEHOST ]; then
 fi
 
 if [ -f $FILESTATIC ]; then
-  echo -e "${YELLOW}Appending Static IDs from ${$FILESTATIC}${NC}"
+  echo -e "${YELLOW}Appending Static IDs from ${FILESTATIC}${NC}"
   sed -i -e 's/\r//' $FILESTATIC
 else
   touch $FILESTATIC
@@ -48,17 +48,17 @@ fi
 countstatic=$(wc --lines ${FILESTATIC} | cut -d" " -f1)
 
 if [ -f ~/keep.seed.file ] && [ -f ~/seeds.zip ]; then
-    cp ~/seeds.zip .
+    cp ~/seeds.zip
 else  
   rm $FILESEEDZIP
 fi
 
 if [ ! -f $FILESEEDZIP ]; then
-  timeout 8 wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/seeds.zip -O $FILESEEDZIP
+  timeout 8 wget --no-check-certificate --wait=3 https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/seeds.zip -O $FILESEEDZIP
 fi
 
 if [ ! -f $FILESEEDZIP ]; then
-  echo -e "${RED}Unable to download seed file for static EU data.${NC}"
+  echo -e "${RED}Unable to download seed file for nickname and extra EU data.${NC}"
   sleep 8
 fi
 
@@ -69,15 +69,23 @@ fi
 if [ -f $FILESEEDZIP ]; then
     if [ -f $FILESEED ]; then
 	  rm $FILESEED
+    fi
+    unzip $FILESEEDZIP $FILESEED
+	if [ "$?" -ne 0 ]; then
+	  echo -e "${RED}Error - Unable to extract from ZIP file ${NC}"
+	  sleep 1
 	fi
-    unzip $FILESEEDZIP $FILESEED >/dev/null
+	if [ ! -f $FILESEED ]; then
+	  echo -e "${RED}Unable to extract compressed file from seed.zip.  The seed.zip did not download or is corrupt.${NC}"
+	  sleep 5
+	  echo -e "${GREEN}Continuing without nickname and extra EU data...${NC}"
+	fi
     cat $FILESEED >>$TMPALL
     if [ -f ~/keep.seed.file ]; then
 		echo -e "${GREEN}Keeping seed file for next ${YELLOW}glv${NC}."
 		echo -e "${GREEN}To force an update next glv: rm ~/keep.seed.file"
 		cp $FILESEEDZIP ~
-		sleep 1
-		
+		sleep 3
 	fi
 	if [ -f ~/keep.tmp ]; then
 	  rm $FILESEED $FILESEEDZIP
@@ -96,15 +104,16 @@ sort -t, -k 1,1 -n $TMPDEDUP >$TMPSORTED
   
 cat $TMPSORTED >~/user.bin
   
-
+countseed=$(wc --lines $FILESEED | cut -d" " -f1)
 countmarc=$(wc --lines ~/md380tools/db/dmrmarc.tmp | cut -d" " -f1)
 countall=$(wc --lines ~/user.bin | cut -d" " -f1)
 echo -e "${GREEN}Contact Import completed."
-echo -e "  Static ID count:  ${countstatic}"
-echo -e "  DMR-MARC count :  ${countmarc}"
-echo -e "  Merged total   :  ${countall}${NC}"
+echo -e "${GREEN}  Seed count     :  ${YELLOW}${countseed}"
+echo -e "${GREEN}  Static ID count:  ${YELLOW}${countstatic}"
+echo -e "${GREEN}  DMR-MARC count :  ${YELLOW}${countmarc}"
+echo -e "${GREEN}  Merged total   :  ${YELLOW}${countall}${NC}"
 if [ -f ~/keep.tmp ]; then
-    echo -e "${RED}Keeping temporary files around for debug${NC}"
+    echo -e "${RED}Keeping temporary files around for debug.  rm ~/keep.tmp to disable this.${NC}"
 else
     rm $TMPALL $TMPSORTED $TMPDEDUP
 fi
